name: Update YouTube M3U8

on:
  schedule:
    - cron: '0 */3 * * *' # প্রতি 3 ঘণ্টা পর পর অটো আপডেট হবে
  workflow_dispatch:      # ম্যানুয়ালি রান করার অপশন (টেস্ট করার জন্য)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Run Script
        run: python update_m3u8.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add live_playlist.m3u8
          git commit -m "Updated M3U8 Playlist [skip ci]" || exit 0
          git push
