name: Update YouTube M3U8

on:
  schedule:
    - cron: '0 */1 * * *' # প্রতি ৬ ঘণ্টা পর পর চলবে
  workflow_dispatch:      # ম্যানুয়ালি চালানোর জন্য

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # ফাইল সেভ করার পারমিশন
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Script
        run: python update_m3u8.py

      - name: Commit and Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add live_playlist.m3u8
          git commit -m "Updated Playlist" || exit 0
          git push
